FROM fedora:42

# Install system dependencies
RUN dnf -y install \
      centpkg \
      curl \
      git \
      python3 \
      python3-pip \
      python3-redis \
      python3-specfile \
      rpmbuild \
      rpmdevtools \
      rpmlint \
      spectool \
    && dnf -y clean all

# https://github.com/i-am-bee/beeai-framework/pull/939
# already merged, can be removed after next upstream release
COPY beeai-gemini.patch /tmp
# https://github.com/i-am-bee/beeai-framework/issues/959
COPY beeai-gemini-malformed-function-call.patch /tmp
# https://github.com/i-am-bee/beeai-framework/issues/906
COPY beeai-instrumentation.patch /tmp

# Install BeeAI Framework and Phoenix
RUN pip3 install --no-cache-dir \
    beeai-framework[mcp,duckduckgo]==0.1.31 \
    openinference-instrumentation-beeai \
    arize-phoenix-otel \
    && cd /usr/local/lib/python3.13/site-packages \
    && patch -p2 -i /tmp/beeai-gemini.patch \
    && patch -p2 -i /tmp/beeai-gemini-malformed-function-call.patch \
    && patch -p5 -i /tmp/beeai-instrumentation.patch

# Create user
RUN useradd -m -G wheel beeai

# Copy required directories
# Individual directories are mounted as volumes in development
COPY agents/ /home/beeai/agents/
COPY common/ /home/beeai/common/
RUN chgrp -R root /home/beeai && chmod -R g+rwX /home/beeai

USER beeai
WORKDIR /home/beeai

ENV PYTHONPATH=/home/beeai

# so that we can start working with gitlab.com immediately
RUN mkdir ~/.ssh \
      && chmod 0700 ~/.ssh \
      && ssh-keyscan gitlab.com >> ~/.ssh/known_hosts \
      && git config --global user.email "jotnar@redhat.com" \
      && git config --global user.name "RHEL Packaging Agent"

CMD ["/bin/bash"]
