TEST_IMAGE ?= beeai-tests
TEST_IMAGE_C9S ?= beeai-tests-c9s
TEST_TARGET ?= ./tests/unit

CONTAINER_ENGINE ?= $(shell command -v podman 2>/dev/null || echo "docker")

.PHONY: build-test-image build-test-image-fedora build-test-image-c9s
build-test-image: build-test-image-fedora build-test-image-c9s

build-test-image-fedora:
	$(CONTAINER_ENGINE) build --rm --tag $(TEST_IMAGE) -f Containerfile.tests

build-test-image-c9s:
	$(CONTAINER_ENGINE) build --rm --tag $(TEST_IMAGE_C9S) -f Containerfile.c9s-tests

.PHONY: check check-agents check-mcp-server check-in-container \
	check-agents-in-container check-mcp-server-in-container check-jira-issue-fetcher-in-container

check-agents:
	cd ./agents && \
	PYTHONPATH=$(CURDIR) PYTHONDONTWRITEBYTECODE=1 python3 -m pytest --verbose --showlocals $(TEST_TARGET)
check-mcp-server:
	cd ./mcp_server && \
	PYTHONPATH=$(CURDIR) PYTHONDONTWRITEBYTECODE=1 python3 -m pytest --verbose --showlocals $(TEST_TARGET)
check-jira-issue-fetcher:
	cd ./jira_issue_fetcher && \
	PYTHONPATH=$(CURDIR) PYTHONDONTWRITEBYTECODE=1 python3 -m pytest --verbose --showlocals $(TEST_TARGET)

check: check-agents check-mcp-server check-jira-issue-fetcher

check-agents-in-container:
	$(CONTAINER_ENGINE) run --rm -it -v $(CURDIR):/src:z --env TEST_TARGET $(TEST_IMAGE_C9S) make -f Makefile.tests check-agents
check-mcp-server-in-container:
	$(CONTAINER_ENGINE) run --rm -it -v $(CURDIR):/src:z --env TEST_TARGET $(TEST_IMAGE) make -f Makefile.tests check-mcp-server
check-jira-issue-fetcher-in-container:
	$(CONTAINER_ENGINE) run --rm -it -v $(CURDIR):/src:z --env TEST_TARGET $(TEST_IMAGE) make -f Makefile.tests check-jira-issue-fetcher

check-in-container: check-agents-in-container check-mcp-server-in-container check-jira-issue-fetcher-in-container
